### ISSUE TITLE
Hent målerdata fra IOT-devices

### ISSUE THREAD

**Issue by st-randers** [Randers-Kommune-Digitalisering/vis-klimadata-initiativer-aktiviteter#127]
```[tasklist]
### Tasks
- [x] Få adgang til OS2IoT
- [x] Undersøg muligheder for at importere data til node-red
- [x] Byg flow til kontinuerlig import af data
- [x] Åbn HTTP endpoint med API-nøgle
- [x] Opret datatarget til endpoint fra OS2IoT
```

Overordnet beskrivelse findes i Digitaliseringsoverblikkets issue vedr. dette projekt: [Målerdata via IOT-devices#123](https://github.com/Randers-Kommune-Digitalisering/vis-klimadata-initiativer-aktiviteter/issues/123).

**Comment by st-randers** [comment]
Muligheder for import af data:
![image](https://github.com/Randers-Kommune-Digitalisering/vis-klimadata-initiativer-aktiviteter/assets/115066094/0c90a1f0-7d53-470d-a377-2c217ca219a5)
1. Generic HTTP push - kræver et offentligt tilgængeligt HTTP endpoint udstilt fra node-red
2. OpenData - kræver at vi udstiller data'en offentligt, og knytter det til en OpenData profil (bruger)
3. FIWARE  connection - ikke relevant
4. MQTT broker - kræver at vi udstiller en MQTT broker offentligt, f.eks. et docker image med adgang fra internettet

**Comment by st-randers** [comment]
@kithosting Kan I hjælpe med at udstille enten et HTTP endpoint eller en MQTT broker som er tilgængelig fra internettet, eller ihvertfald fra OS2IoT's servere? 

Hvis jeg f.eks. laver et HTTP endpoint i node-red, hvordan udstiller jeg så dette offentligt? Eller alternativt en containerized MQTT service? Er det overhovedet muligt at gøre sikkert?

**Comment by bork91** [comment]
Hej Søren

Skal vi se på at lave et HTTP endpoint?
Hvordan med sikkerhed tænker det skal være noget auth på? Hvad understøtter de enheder, skal der pushes til HTTP endpoint af sikkerhed?

Her er et yaml eksemple på en ingress config der modtager https:
service:
  ingress:
    enabled: true
    annotations:
      [cert-manager.io/cluster-issuer](http://cert-manager.io/cluster-issuer): letsencrypt-prod
    hosts:
      - host: [myendpint.randers.t0.hosting.kitkube.dk](http://myendpint.randers.t0.hosting.kitkube.dk/)
        paths:
          - path: /
    tls:
      - hosts:
          - myendpint.[randers.t0.hosting.kitkube.dk](http://randers.t0.hosting.kitkube.dk/)
        secretName: myendpint.[randers.t0.hosting.kitkube.dk](http://randers.t0.hosting.kitkube.dk/)

**Comment by st-randers** [comment]
@bork91 Hej Morten, tak for dit svar!

Ift. sikkerhed understøtter OS2Iot "HTTP basic Auth; or a secret header/url-parameter definded by the user, configured in OS2IoT" iflg. deres egen dokumentation som findes her: https://os2iot.readthedocs.io/en/latest/external-interface-design/external-interface-design.html#id2

Vi kæmper lige med adgangsstyring til OS2Iot i dag, men jeg kigger lige nærmere på det når vi får styr på det igen.

Hvad foreslår I ift. sikkerhed?

**Comment by bork91** [comment]
@st-randers 
I K8S kan vi opsætte HTTP basic Auth. Der er en guide til det her: https://kubernetes.github.io/ingress-nginx/examples/auth/basic/ 
API key er noget appliokationen skal håndtere. Det kan være at validere nøglen med en liste af nøgler der kommer ind som env.

Hvilken en af to der vælges ser jeg ikke have den store betydning for sikkerheden.

**Comment by st-randers** [comment]
@bork91 

Det lyder fint, men jeg tror stadig at skal bruge lidt hjælp til hele opsætningen.

Jeg forsøger at implementere løsningen på den branch som dette issue linker til. Her har jeg tilføjet det YAML eksempel som du gav, og rettet "myendpoint" som det eneste. Jeg kan dog ikke køre "docker compose up" med denne ændring I Codespace, da jeg så får følgende fejl: 

- Additional property "enabled" is not allowed
- Additional property "hosts" is not allowed
- Additional property "tls" is not allowed

Fjerner jeg så alle 3 properties fra YAML'en, får jeg følgende fejl:
- service "ingress" has neither an image nor a build context specified: invalid compose project

Definerer jeg så et image, f.eks. "nginx/nginx-ingress" så kan jeg køre en docker compose up - så længe ingen af de fornævnte properties er defineret. Men det kan jeg jo godt regne ud, ikke er måden det skal gøres på.
Sker fejlen fordi jeg forsøger at køre det i GitHub codespace, som har sin egen nginx/ingress?

Ift. sikkerheden, er det fint med HTTP basic auth - men det skal jeg nok også bruge hjælp til, da jeg ikke har erfaring med hverken kubernetes eller ingress opsætning.

Kan vi sætte et møde op hvor vi kan kigge på det sammen, eller kan du hjælpe med at lave disse ændringer direkte i repo'et? Du kan lave en ny branch ud fra 127-hent-målerdata-fra-iot-devices (eller bare ændre direkte i denne branch så længe der kun er tale om docker-compose filen etc. - den er alligevel broken lige nu med førnævnte fejl).

**Comment by bork91** [comment]
@st-randers 
Det yaml jeg sendte er til Kubernetes og vores service Helm chart.

Jeg ved ikke lige hvordan og om det er muligt i codespace. 
Tænker at i codespace er det bedst practise at lave nogle integrationstest selv. Når koden så er klar kan det lægges i prototypes (K8S), hvor vi så kan få OSiot til at kalde ind mod servicen med hjælp fra K8S.

**Comment by st-randers** [comment]
@bork91 
Det er nok ikke muligt i CodeSpace nej. Koden er sådan set klar, ihvertfald klar til test med live data. 

Jeg har flyttet yaml configurationen af ingress servicen til en fil for sig selv - "k8-deploy.yml". Hvordan henviser jeg til denne configuration i argo? Jeg har synced således det nyeste commit er på test.

**Comment by bork91** [comment]
@st-randers jeg har inviteret dig til et møde i morgen hvor vi kan gøre det sammen :)

**Comment by cbh-randers** [comment]
```[tasklist]
### Tasks
- [x] Få adgang til OS2IoT
- [x] Undersøg muligheder for at importere data til node-red
- [x] Byg flow til kontinuerlig import af data
- [x] Åbn HTTP endpoint med API-nøgle
- [x] Opret datatarget til endpoint fra OS2IoT
```
