### ISSUE TITLE
Klimamonitor indikator 3.1: Vomgasser

### ISSUE THREAD

**Issue by ghost** [Randers-Kommune-Digitalisering/vis-klimadata-initiativer-aktiviteter#16]
Måltal 2030: 15% ned fra 2018 niveau

```[tasklist]
### Indikator opgaver
- [x] Definer titel
- [x] Definer visualiserings type
- [x] Definer datakilde til måltal
- [x] https://github.com/Randers-Kommune-Digitalisering/vis-klimadata-initiativer-aktiviteter/issues/17
```

**Comment by kf-randers** [comment]
Afventer pt. opdaterede data fra PlanEnergi

**Comment by kf-randers** [comment]
Visualisering tilføjet superset
https://superset.prototypes.randers.dk/superset/dashboard/p/Ma0o8kXWQvq/
