### ISSUE TITLE
Forecasting på tidsserie data

### ISSUE THREAD

**Issue by jmk-randers** [Randers-Kommune-Digitalisering/vis-klimadata-initiativer-aktiviteter#30]
_Til styregruppemøde torsdag d. 16 marts 2023 var der stor interesse fra Økonomidirektøren og styregruppen for at kunne lave forecasting på data i klimamonitoren.
Dette issue holder opgaverne der er knyttet til at få dette til at fungere._

```[tasklist]
### Tasks
- [x] Selvstudier og research på Prophet, hvordan intergreres og betjenes modulet?
- [ ] https://github.com/Randers-Kommune-Digitalisering/vis-klimadata-initiativer-aktiviteter/issues/32
- [ ] Test af forecasting på prototypes
```

**Comment by jmk-randers** [comment]
COMMUNITY, SUPERSET GUIDE
[How Prophet Enables Time-Series Forecasting in Superset](https://preset.io/blog/2021-3-22-druid-prophet-pt3/)

**Comment by jmk-randers** [comment]
Explain Like I'm 5: Prophet -> [Meta Open Source](https://www.youtube.com/@FacebookOpenSource)


https://facebook.github.io/prophet/

**Comment by jmk-randers** [comment]
@kf-randers: Skal vi teste det sammen på nogle charts til næste fælles arbejds-session?

**Comment by kf-randers** [comment]
@jmk-randers: Jeg kaster mig over at test funktionaliteten, når jeg har adgang til SQL Lab. Det giver ikke så meget mening at lave forecastet på en andel i denne sammenhæng.

**Comment by kf-randers** [comment]
Jeg kan desværre ikke få det til at virke. Prøve at forecaste antal_elbiler i datasættet klima.5.1. Jeg ved ikke om problemet kan være, at der ikke er datapunkter nok. 

![Image](https://github.com/Randers-Kommune-Digitalisering/vis-klimadata-initiativer-aktiviteter/assets/122357806/de2f59ed-d0cd-482f-bf98-7d67b3ba79e3)

**Comment by kf-randers** [comment]
Det virker
