### ISSUE TITLE
Brændstof-regnskab

### ISSUE THREAD

**Issue by IndraZT** [Randers-Kommune-Digitalisering/vis-klimadata-initiativer-aktiviteter#36]
```[tasklist]
### Tasks
- [x] Find datakilde
- [x] Udnævn dataejer
- [x] Fjern flere kolonner
- [x] Læg data på Opendata
- [ ] https://github.com/Randers-Kommune-Digitalisering/vis-klimadata-initiativer-aktiviteter/issues/46
```

**Comment by IndraZT** [comment]
Hej. Jeg har uploadede brændstofdata her https://admin.opendata.dk/dataset/test-braendstof

-Vi skal tage stilling om data skal indskrænkes: skal navnene på afdelingerne med? skal leverandørnes navne med? skal det opdeles per år?

-Skal jeg undersøge om vi skal sende data automatisk fra indkøbssystemet til visualiserings værktøjet.

**Comment by IndraZT** [comment]
1. Kommentarer til datasættet:

- Vi har besluttet at datasættet skal minimeres. Kolonner vi beholder: 

> Dato 
> Varetekst
> Antal enheder
> Fakturaenhed
> Beløb
> Faktura basis pris
> UNSPSC
> UNSPSC navn

- Svar på nogle undringspunkter fra sidste møde:
> Min kollega har beriget data med en ekstra kolonne 'Type' fordi der er nogle varelinjer uden UNSPSC kode på (der er tale omkring 4% af beløbet) derfor vil der være ca. 4% af data der vil mangle hvis vi trækker data automatisk fra indkøbssystemet som pt. er TrueAnalyze
> det er rigtigt at den officielle UNSPSC kode hedder 'Nr. 2 Brændselsolie til opvarmning'

2.  Jeg er i gang med at minimere datasættet og splitte det op på år.
3. Næste skrid er at uploade det på OpenData igen

**Comment by IndraZT** [comment]
@jmk-randers  nu er det nye data op på opendata. Vil du se om du kan gøre det synligt i Superset? (og jeg må meget gerne få adgang til det dataset)

**Comment by jmk-randers** [comment]
Hej @IndraZT, hvis det skal trækkes automatiskt skal det være et public dataset. Hvis du som dataejer kan godkende at det er ikke følsom data, så er det bare at ændre det fra Private til Public, så kan jeg trække data ned i prototype databasen

**Comment by IndraZT** [comment]
Hej @jmk-randers Jeg var ikke på arbejde i går , så jeg så det ikke. Men som jeg skrev i Teams, har jeg ikke et problem med at det ligger offentligt, jeg har bare behov for at vide hvor meget vil Lars blandes ind i det. Så når Karl svarer, gør jeg data offentlig.

**Comment by jmk-randers** [comment]
Efter statusmøde blev vi enige om følgende:

"Varetekst" kolonnen fjernes da den ikke indeholder data der er relevant for klimamonitorering og evt. kan udstille data der kan identificere bl.a. indkøbsaftaler.

"Fakturaenhed" kolonnen fjernes - da den ikke kan bruges

"Beløb" og "Faktura basis pris" fjernes da det ikke er til en økonomisk analyse, men analyse af mængder og de potentielt kan udstille indkøbsmønstre.

**Comment by IndraZT** [comment]
Så er der kommet data op https://admin.opendata.dk/dataset/braendstofforbrug

Jeg har også kigget på hver af dem for at være sikker på at det er den rigtig fil. 

Får du det op i superset @jmk-randers ?

**Comment by jmk-randers** [comment]
Jeg får nu data ind, men kan ikke lave automatisk database indsættelse da der er mellemrum i flere kolonnenavne i datasættet. ("Antal enheder" og "UNSPC navn")

Den hurtigeste og nemmeste løsning er at få skrevet ind i guiden at man ikke må bruge mellemrum i kolonnenavne (hvis det ikke allerede står der?) og så rette brændstof-data til på opendata manuelt... 

Den lidt mere langhårede er at jeg laver noget kode der prøver at rette folks indtastningsfejl dynamisk inden koden til databaseindsættelse kører...

@kf-randers: What do do?

**Comment by jmk-randers** [comment]
Jeg har tjekket med andre datasæt og f.eks i #18 er derbogså paranteser, bindestreger og danske karakterer i kolonnenavnene.

@kf-randers @akk-randers : Jeg udvikler et lille stump kode der erstatter alle specialtegn i et datasæt med "_" inden det skrives i databasen. Så skal det skrives i vores guide at det er derfor deres datasæt ser anderledes ud når det rammer klimamonitoren.

Så kan jeg komme videre med at lave en mere generisk Opendata integration.

**Comment by jmk-randers** [comment]
@kf-randers, @CamillaOS:

Hej, første version af connectoren til OpenData skriver nu brændstof data i databasen.

I kan lave relevante datasæt ud fra tabellen "opendata_braendstofforbrug"

![image](https://github.com/Randers-Kommune-Digitalisering/vis-klimadata-initiativer-aktiviteter/assets/80261692/1abc15d3-b7a2-457d-9e7a-17dc31b8f681)

I må meget gerne teste om data er som i forventer og lukke dette issue som færdigt, med en kommentar hvis alt lever op til forventningerne!
