### ISSUE TITLE
Dataintegrationer med energidata fra Verdo

### ISSUE THREAD

**Issue by ghost** [Randers-Kommune-Digitalisering/vis-klimadata-initiativer-aktiviteter#44]
```[tasklist]
### Tasks
- [x] Opstartsmøde med Verdo
- [ ] Drøftelse af samarbejdsform - møde sættes op
- [ ] Statusmøde i starten af september
```
```[tasklist]
### Tasks
```

**Comment by tna-randers** [comment]
Verdo undersøger, om de kan understøtte følgende mål fra Klimaplanen med data: 

DELMÅL 9: FOSSILFRIE KRAFTVARMEVÆRKER	9.1: Andel fossilfrie kraftvarmeværker
DELMÅL 10: UDFASNING AF OLIE OG NATURGAS TIL INDIVIDUEL OPVARMNING	10.1: Antal olie og naturgasfyr
DELMÅL 11: VE-ANLÆG, DER DÆKKER BEHOVET FOR ENERGI	11.1: Energiproduktion på VE-anlæg i andel af eget forbrug
DELMÅL 11: VE-ANLÆG, DER DÆKKER BEHOVET FOR ENERGI	11.2: Elproduktion på VE-anlæg (TJ)

Som koncern er vi interesserede i: 

DELMÅL 22: KLIMAVENLIGT ENERGIFORBRUG	22.1: El- og varmeforbrug pr. m2 (KJ)
DELMÅL 22: KLIMAVENLIGT ENERGIFORBRUG	22.2: Antal kommunalt ejede olie- og gasfyr

**Comment by tna-randers** [comment]
Verdo vil fremsende en beskrivelse af udfordring med geografiske adressedata, som Randers Kommune vedligeholder.

**Comment by tna-randers** [comment]
Tom tager fat i Verdo og hører om projektet skal videreføres. @tna-randers

**Comment by tna-randers** [comment]
Sagen afvises da Verdo ikke er vendt tilbage.
