### ISSUE TITLE
Klimamonitor indikator 13.1: Andel indsamlet emballageplast fra husholdningerne

### ISSUE THREAD

**Issue by kf-randers** [Randers-Kommune-Digitalisering/vis-klimadata-initiativer-aktiviteter#85]
- [x] Kontakt Affald og Genbrug mht. 
- [ ] Find datakilde
- [ ] Etabler forbindelse til databilde
- [ ] Opret chart i Superset
