### ISSUE TITLE
Klimamonitor indikator 13.3: Indsamlet madaffald fra husholdningerne (ton)

### ISSUE THREAD

**Issue by kf-randers** [Randers-Kommune-Digitalisering/vis-klimadata-initiativer-aktiviteter#87]
- [x] Kontakt Affald og Genbrug mht. 
- [ ] Find datakilde
- [ ] Etabler forbindelse til databilde
- [ ] Opret chart i Superset
